language: cpp
os: linux
dist: xenial
sudo: required
compiler:
  - gcc
before_install:
    - eval "${MATRIX_EVAL}"
    - wget https://www.libsdl.org/release/SDL2-2.0.9.tar.gz -O SDL2-2.0.9.tar.gz
    - tar -xzvf SDL2-2.0.9.tar.gz
    - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.4.tar.gz -O SDL2_image-2.0.4.tar.gz
    - tar -xzvf SDL2_image-2.0.4.tar.gz
    - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz -O SDL2_ttf-2.0.15.tar.gz
    - tar -xzvf SDL2_ttf-2.0.15.tar.gz
    - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz -O SDL2_mixer-2.0.4.tar.gz
    - tar -xzvf SDL2_mixer-2.0.4.tar.gz
install:
    - (cd SDL2-2.0.9 && ./configure && make && sudo make install && cd ..)
    - (cd SDL2_image-2.0.4 && ./configure && make && sudo make install && cd ..)
    - (cd SDL2_ttf-2.0.15 && ./configure && make && sudo make install && cd ..)
    - (cd SDL2_mixer-2.0.4.tar.gz && ./configure && make && sudo make install && cd ..)
script: |
  mkdir -p intermediate
  cd intermediate
  cmake .. -DCMAKE_BUILD_TYPE=Debug
  make
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libglew-dev
            - libxmu-dev
            - libxi-dev
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"