language: cpp
os: linux
dist: xenial
sudo: required
compiler:
  - gcc
before_install:
    - eval "${MATRIX_EVAL}"
    - wget https://www.libsdl.org/release/SDL2-2.0.9.zip -O SDL2.tar.gz
    - tar -xzvf SDL2.tar.gz
install:
    - (cd SDL2 && ./configure && make && sudo make install)
script: |
  mkdir -p intermediate
  cd intermediate
  cmake .. -DCMAKE_BUILD_TYPE=Debug
  make
# install: apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libglew-dev libxmu-dev libxi-dev
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - libsdl2-ttf-dev
            - libglew-dev
            - libxmu-dev
            - libxi-dev
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"