language: cpp
os: linux
dist: trusty
sudo: required
compiler:
  - gcc
script: mkdir -p intermediate; cd intermediate; cmake .. -DCMAKE_BUILD_TYPE=Debug; make
# install: apt install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0 libglew-dev libxmu-dev libxi-dev
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl2-2.0-0
            - libsdl2-image-2.0-0
            - libsdl2-mixer-2.0-0
            - libsdl2-ttf-2.0-0
            - libglew-dev
            - libxmu-dev
            - libxi-dev
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"