language: cpp
os: linux
dist: trusty
sudo: required
compiler:
  - gcc
  - clang
script: mkdir -p intermediate; cd intermediate; cmake .. -DCMAKE_BUILD_TYPE=Debug; make
# install: apt install freeglut3-dev libglew-dev libxmu-dev libxi-dev
addons:
  apt:
    packages:
    - freeglut3-dev
    - libglew-dev
    - libxmu-dev
    - libxi-dev
    - cmake
    - gcc
    - g++
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"