version: 1.0.{build}
configuration: Debug
platform: x64
image:
- Visual Studio 2015
- Visual Studio 2017
install:
  - ps: >-
      function Expand-ZIPFile($file, $destination)
      {
        $shell = new-object -com shell.application
        $zip = $shell.NameSpace($file)
        foreach($item in $zip.items())
        {
          $shell.Namespace($destination).copyhere($item)
        }
      }
      New-Item -ItemType Directory -Force -Path dependencies
      (new-object net.webclient).DownloadFile('https://github.com/RicardoEPRodrigues/Dependencies/raw/master/glew-msvc.zip', 'glew-msvc.zip')
      Expand-ZIPFile –File .\glew-msvc.zip –Destination .\dependencies
      (new-object net.webclient).DownloadFile('https://github.com/RicardoEPRodrigues/Dependencies/raw/master/freeglut-msvc.zip', 'freeglut-msvc.zip')
      Expand-ZIPFile –File .\freeglut-msvc.zip –Destination .\dependencies
