version: 1.0.{build}
configuration: Debug
platform: x64
image:
- Visual Studio 2015
- Visual Studio 2017
install:
  - ps: >-
      (new-object net.webclient).DownloadFile('https://github.com/RicardoEPRodrigues/Dependencies/raw/master/glew-msvc.zip', 'glew-msvc.zip')
      Expand-Archive .\glew-msvc.zip -DestinationPath .\dependencies
      (new-object net.webclient).DownloadFile('https://github.com/RicardoEPRodrigues/Dependencies/raw/master/freeglut-msvc.zip', 'freeglut-msvc.zip')
      Expand-Archive .\freeglut-msvc.zip -DestinationPath .\dependencies
