version: 1.0.{build}
configuration: Debug
platform: x64
image:
- Visual Studio 2017
install:
  - ps: New-Item -ItemType Directory -Force -Path dependencies
  - ps: (new-object net.webclient).DownloadFile('https://github.com/RicardoEPRodrigues/Dependencies/raw/master/glew-msvc.zip', 'glew-msvc.zip')
  - ps: (new-object net.webclient).DownloadFile('https://github.com/RicardoEPRodrigues/Dependencies/raw/master/freeglut-msvc.zip', 'freeglut-msvc.zip')
  - ps: Expand-Archive .\glew-msvc.zip –DestinationPath .\dependencies
  - ps: Expand-Archive .\freeglut-msvc.zip –DestinationPath .\dependencies
